### PR TITLE
Fix `GenConsumer.handle_call` default implementation

### LINKED ISSUE #237: Default implementation of GenConsumer's handle_call fails dialyzer
The callback spec says the implementation must return a `{:reply...}` tuple, but the default implementation returns an atom.  This causes dialyzer to error out if the user does not implement a callback.

### PR DESCRIPTION
**Pull request by dantswain**
Fixes #237

The previous implementation causes a dialyzer error if the user does not
implement a handle_call.  This version is taken from the
GenServer.handle_call default implementation.

### CODE REVIEW

File: lib/kafka_ex/gen_consumer.ex [hunk 1]
```diff
@@ -262,9 +262,20 @@ defmodule KafkaEx.GenConsumer do
...
+          {_, []}   -> self()
+          {_, name} -> name
+        end
+
+        # We do this to trick Dialyzer to not complain about non-local returns.
+        case :erlang.phash2(1, 1) do
+          0 ->
+            raise "attempted to call GenServer #{inspect proc} but no " <>
+              "handle_call/3 clause was provided"
+          1 -> {:reply, {:bad_call, msg}, consumer_state}
```
Comment (joshuawscott) [inline lib/kafka_ex/gen_consumer.ex]: consumer_state isn't a valid identifier here, wouldn't this cause a compile warning?

File: lib/kafka_ex/gen_consumer.ex [hunk 2]
```diff
@@ -262,9 +262,20 @@ defmodule KafkaEx.GenConsumer do
         {:ok, nil}
       end
 
-      def handle_call(_call, _from, _consumer_state) do
-        # the user must implement this if they expect to recieve calls
-        :handle_call_not_implemented
+      def handle_call(msg, _from, _consumer_state) do
+        # taken from the GenServer handle_call implementation
+        case Process.info(self(), :registered_name) do
```
Comment (joshuawscott) [inline lib/kafka_ex/gen_consumer.ex]: I think this is missing the `proc = case ...`

File: lib/kafka_ex/gen_consumer.ex (hunk 1 above)
Comment (dantswain) [reply lib/kafka_ex/gen_consumer.ex]: :rage1:  Added a test, pushed fixes, waiting for travis.

File: lib/kafka_ex/gen_consumer.ex [hunk 3]
```diff
@@ -262,9 +262,20 @@ defmodule KafkaEx.GenConsumer do
...
+        # taken from the GenServer handle_call implementation
+        proc = case Process.info(self(), :registered_name) do
+          {_, []}   -> self()
+          {_, name} -> name
+        end
+
+        # We do this to trick Dialyzer to not complain about non-local returns.
+        case :erlang.phash2(1, 1) do
+          0 ->
+            raise "attempted to call GenServer #{inspect proc} but no " <>
```
Comment (bjhaid) [inline lib/kafka_ex/gen_consumer.ex]: `GenServer` should be `GenConsumer`

File: lib/kafka_ex/gen_consumer.ex (hunk 1 above)
Comment (bjhaid) [reply lib/kafka_ex/gen_consumer.ex]: do we need to actually return something here, it seems this will never match at least from me running in erl, is `_ -> _ # with some comment` not adequate?

File: lib/kafka_ex/gen_consumer.ex (hunk 3 above)
Comment (dantswain) [reply lib/kafka_ex/gen_consumer.ex]: Good catch

File: lib/kafka_ex/gen_consumer.ex (hunk 1 above)
Comment (dantswain) [reply lib/kafka_ex/gen_consumer.ex]: It should never return this in practice, but I think it's necessary for it to return a value within the dialyzer spec so that dialyzer succeeds.  I assume they did this on purpose in the GenServer implementation.

Comment (bjhaid) [reply lib/kafka_ex/gen_consumer.ex]: Ah I see, how about `_ -> {:reply, {:bad_call, msg}, consumer_state}` so the int `1` is less confusing, it's annoying to have write dumb code to just make dialyzer happy
